-- Create Market Items Table
create table if not exists public.market_items (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  expires_at timestamp with time zone default timezone('utc'::text, now() + interval '48 hours') not null,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  price text not null,
  image_url text,
  contact_info text not null,
  author_name text
);

-- Enable RLS
alter table public.market_items enable row level security;

-- Policies

-- 1. Everyone can view active items (not expired)
create policy "Anyone can view active items" 
on public.market_items for select 
using (expires_at > timezone('utc'::text, now()));

-- 2. Users can view ALL their own items (active or expired)
create policy "Users can view own items" 
on public.market_items for select 
using (auth.uid() = user_id);

-- 3. Authenticated users can insert items
create policy "Users can insert items" 
on public.market_items for insert 
with check (auth.uid() = user_id);

-- 4. Users can update their own items (for renewal)
create policy "Users can update own items" 
on public.market_items for update 
using (auth.uid() = user_id);

-- 5. Users can delete their own items
create policy "Users can delete own items" 
on public.market_items for delete 
using (auth.uid() = user_id);
