-- Create Messages Table (Fix)
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.messages enable row level security;

-- Policies for Messages

-- 1. Users can view messages they sent or received
drop policy if exists "Users can view own messages" on public.messages;
create policy "Users can view own messages" 
on public.messages for select 
using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- 2. Users can send messages
drop policy if exists "Users can insert messages" on public.messages;
create policy "Users can insert messages" 
on public.messages for insert 
with check (auth.uid() = sender_id);

-- 3. Users can update messages (mark as read)
drop policy if exists "Users can update messages" on public.messages;
create policy "Users can update messages" 
on public.messages for update 
using (auth.uid() = receiver_id);

-- Enable Realtime for Messages
begin;
  -- Remove table from publication if it exists to avoid error, then add it back
  -- Or just add it and ignore error? Simpler to just ensure publication exists.
  -- Safe approach:
  alter publication supabase_realtime add table public.messages;
exception when others then
  -- In case publication doesn't exist, create it
  create publication supabase_realtime for table public.messages;
end;
