-- Create Friendships Table (Updated with Names)
create table if not exists public.friendships (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  friend_id uuid references auth.users not null,
  requester_name text, -- Name of the user_id (requester)
  receiver_name text, -- Name of the friend_id (receiver)
  status text not null check (status in ('pending', 'accepted', 'blocked', 'market')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, friend_id)
);

-- Create Messages Table
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid references auth.users not null,
  receiver_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
alter table public.friendships enable row level security;
alter table public.messages enable row level security;

-- Policies for Friendships

-- 1. Users can view their own friendships (either as requester or receiver)
create policy "Users can view own friendships" 
on public.friendships for select 
using (auth.uid() = user_id or auth.uid() = friend_id);

-- 2. Users can insert friend requests (as user_id)
create policy "Users can insert friend requests" 
on public.friendships for insert 
with check (auth.uid() = user_id);

-- 3. Users can update status (accept requests)
create policy "Users can update friendship status" 
on public.friendships for update 
using (auth.uid() = user_id or auth.uid() = friend_id);

-- 4. Users can delete friendships (unfriend/cancel)
create policy "Users can delete friendships" 
on public.friendships for delete 
using (auth.uid() = user_id or auth.uid() = friend_id);


-- Policies for Messages

-- 1. Users can view messages they sent or received
create policy "Users can view own messages" 
on public.messages for select 
using (auth.uid() = sender_id or auth.uid() = receiver_id);

-- 2. Users can send messages
create policy "Users can insert messages" 
on public.messages for insert 
with check (auth.uid() = sender_id);

-- 3. Users can update messages (mark as read)
create policy "Users can update messages" 
on public.messages for update 
using (auth.uid() = receiver_id);

-- ENABLE REALTIME (Crucial for Chat)
begin;
  drop publication if exists supabase_realtime;
  create publication supabase_realtime;
commit;
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.friendships;
