-- Create the table for guides
create table public.guides (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  author_id uuid references auth.users not null,
  author_name text not null,
  media_url text,
  media_type text, 
  likes bigint default 0,
  tags text[]
);

-- Enable Row Level Security (RLS)
alter table public.guides enable row level security;

-- Policy: Everyone can view guides
create policy "Guides are viewable by everyone" 
on public.guides for select 
using ( true );

-- Policy: Authenticated users can insert guides
create policy "Users can insert their own guides" 
on public.guides for insert 
with check ( auth.uid() = author_id );

-- Policy: Users can update likes (simplified for prototype)
-- In a real production app, we would use a separate 'likes' table to track who liked what.
-- For this prototype, we'll allow anyone to update the like count mostly for simplicity.
create policy "Anyone can update guides (for likes)"
on public.guides for update
using ( true );
